"""Texts of the validation report, English and Traditional Chinese. tests/test_validation.py checks the keys and placeholders match."""

EN = {
    "title": "Verification and validation of the analysis software",
    "subtitle": "AIAG-VDA SPC Manual, draft 11.2 (IATF 16949, 7.1.5.2.1)",
    "meta": "Run {id}, {at}, by {by}",
    "engine": "Program version {engine}; Python {python}, NumPy {numpy}, SciPy {scipy}",
    "digest": "SHA-256 of the record",
    "verdict": "Result",
    "verdict_pass": "Verification passed; validation passed for the reference cases listed.",
    "verdict_verified": "Verification passed. No reference cases of the user exist: validation for the intended use is NOT shown.",
    "verdict_fail": "Not passed: {n} check(s) failed.",
    "terms": "Verification (ISO 9000, 3.8.12) confirms by objective evidence that specified requirements are fulfilled: here, the calculations against references from outside this program. Validation (3.8.13) confirms that the requirements of a specific intended use are fulfilled: here, the reference cases of the user, run with their own settings. The draft calls verification necessary and validation sufficient.",
    "params": "Parameters of the analysis (defaults)",
    "params_note": "Every analysis result and every report carries the settings it was made with. Customer profiles store customer-specific sets.",
    "verification": "Verification: built-in checks",
    "validation": "Validation: reference cases of the user",
    "no_cases": "No reference cases. Enter cases with their data, settings and the results expected from a named source, for example the examples of ISO/TR 11462-3 (the data is sold with the standard and is not part of this program).",
    "col_id": "No.", "col_area": "Area", "col_requirement": "Requirement", "col_reference": "Reference", "col_expected": "Expected", "col_actual": "Found", "col_tol": "Tolerance", "col_result": "Result",
    "ok": "passed", "bad": "FAILED", "summary": "{passed} of {total} checks passed",
    "case_source": "Source of the expected results: {source}",
    "tol_rel": "{tol} relative", "tol_abs": "{tol} absolute", "tol_equal": "equal",
    "limits": "Limits: the built-in checks cover the calculations listed here, not every function of the program. A passed run shows the state of this program version on this system on the day of the run; run it again after every update or change of parameters and keep the records.",
    "area.constants": "Constants", "area.indices": "Indices", "area.precision": "Large and small numbers", "area.charts": "Control limits", "area.signals": "Signals",
    "area.sequential": "CUSUM", "area.msa": "Measurement system analysis", "area.transparency": "Parameters", "area.archive": "Archive", "area.iso11462": "ISO/TR 11462-3 scenarios (constructed)",
    "req.constant": "published factor reproduced", "req.mean": "mean", "req.sd": "standard deviation", "req.pp": "Pp", "req.ppk": "Ppk", "req.ci": "confidence interval of the index",
    "req.ppm": "nonconforming parts per million", "req.scale": "no dependence on unit", "req.offset": "no loss of digits at a large offset", "req.limits": "control limits",
    "req.signal": "out-of-control value found", "req.no_signal": "no false signal in stable data", "req.arl": "average run length", "req.grr": "gauge R&R", "req.params": "all parameters are in the result",
    "req.repeat": "repeatable result", "req.fingerprint": "parameter fingerprint follows the settings", "req.archive": "archive integrity", "req.archive_tamper": "tampering is detected",
    "req.reproduce": "result reproducible from the archive", "req.scenario_normal": "index of a normal process", "req.scenario_skew": "capability of a skewed process (quantile method)", "req.scenario_drift": "time-dependent model found", "req.scenario_changing": "changing location recognised", "req.scenario_states": "tests for several states", "req.runs": "the check runs", "req.custom": "expected result of the reference case",
}

ZH = {
    "title": "分析軟體的查證與確效",
    "subtitle": "AIAG-VDA SPC 手冊草案 11.2（IATF 16949，7.1.5.2.1）",
    "meta": "執行 {id}，{at}，由 {by}",
    "engine": "程式版本 {engine}；Python {python}、NumPy {numpy}、SciPy {scipy}",
    "digest": "紀錄的 SHA-256",
    "verdict": "結果",
    "verdict_pass": "查證通過；所列參考案例的確效通過。",
    "verdict_verified": "查證通過。使用者沒有參考案例：未顯示針對預期用途的確效。",
    "verdict_fail": "未通過：{n} 項檢查失敗。",
    "terms": "查證（ISO 9000，3.8.12）是以客觀證據確認指定要求已被滿足：此處是把計算與本程式以外的參考值比對。確效（3.8.13）是確認特定預期用途的要求已被滿足：此處是使用者的參考案例，用他們自己的設定執行。草案說查證是必要條件，確效才足以證明適用。",
    "params": "分析參數（預設值）",
    "params_note": "每個分析結果與每份報告都帶著它所用的設定。客戶專屬的參數組存在客戶設定檔中。",
    "verification": "查證：內建檢查",
    "validation": "確效：使用者的參考案例",
    "no_cases": "沒有參考案例。請輸入案例，附上資料、設定與來自明確來源的預期結果，例如 ISO/TR 11462-3 的範例（資料隨標準販售，不在本程式內）。",
    "col_id": "編號", "col_area": "範圍", "col_requirement": "要求", "col_reference": "參考來源", "col_expected": "預期", "col_actual": "實得", "col_tol": "容許差", "col_result": "結果",
    "ok": "通過", "bad": "失敗", "summary": "{total} 項檢查中 {passed} 項通過",
    "case_source": "預期結果的來源：{source}",
    "tol_rel": "相對 {tol}", "tol_abs": "絕對 {tol}", "tol_equal": "須相等",
    "limits": "限制：內建檢查涵蓋此處列出的計算，不是程式的每項功能。通過只代表此程式版本在此系統、執行當日的狀態；每次更新或變更參數後都應重跑，並保存紀錄。",
    "area.constants": "常數", "area.indices": "指標", "area.precision": "大數與小數", "area.charts": "管制界限", "area.signals": "訊號",
    "area.sequential": "CUSUM", "area.msa": "量測系統分析", "area.transparency": "參數", "area.archive": "封存", "area.iso11462": "ISO/TR 11462-3 情境（自行構造）",
    "req.constant": "重現公開的係數", "req.mean": "平均值", "req.sd": "標準差", "req.pp": "Pp", "req.ppk": "Ppk", "req.ci": "指標的信賴區間",
    "req.ppm": "每百萬不良數", "req.scale": "不受單位影響", "req.offset": "大偏移量下不損失位數", "req.limits": "管制界限",
    "req.signal": "找出失控的值", "req.no_signal": "穩定資料不誤報", "req.arl": "平均連串長度", "req.grr": "量具 R&R", "req.params": "所有參數都在結果中",
    "req.repeat": "結果可重複", "req.fingerprint": "參數指紋隨設定改變", "req.archive": "封存完整性", "req.archive_tamper": "竄改會被發現",
    "req.reproduce": "可由封存重現結果", "req.scenario_normal": "常態製程的指標", "req.scenario_skew": "偏態製程的能力（分位數法）", "req.scenario_drift": "找出時間相依模型", "req.scenario_changing": "辨識出位置在變動", "req.scenario_states": "多狀態檢定", "req.runs": "檢查可執行", "req.custom": "參考案例的預期結果",
}
