"""Report texts in English and Traditional Chinese.

Placeholders use {name}. tests/test_report.py checks that both languages have the same keys and the
same placeholders, and that every key used by the code exists.
"""

from __future__ import annotations

LANGUAGES = ("zh-TW", "en")

EN = {
    "doc.title": "Process study report",
    "doc.subtitle": "Machine performance, process performance and process capability (AIAG-VDA SPC Manual)",
    "doc.report_id": "Report no.",
    "doc.created": "Created",
    "doc.stage_machine": "Study type: machine performance (Pm/Pmk)",
    "doc.stage_preliminary": "Study type: preliminary process performance (Pp/Ppk)",
    "doc.stage_production": "Study type: process performance or capability (Pp/Ppk or Cp/Cpk)",
    "doc.element": "Element",
    "doc.list_sep": ", ",
    "doc.not_given": "not given",
    "doc.not_applicable": "not applicable",
    "doc.yes": "yes",
    "doc.no": "no",
    "doc.annex_a": "Annex A: values marked invalid",
    "doc.annex_b": "Annex B: traceability",
    "doc.form": "Form", "v.revision": "Rev.", "doc.customer_fields": "Information required by {name}",
    "f.profile": "Customer profile", "f.profile_deviations": "Settings that differ from the profile", "v.none": "none",
    "doc.agreed": "The format and content of this report are to be agreed between customer and supplier.",
    "doc.draft_note": "Calculated after the AIAG-VDA SPC Yellow Volume draft (February 2026). Targets are examples unless the customer agreement states others.",
    "doc.final_note": "Targets use the rules of the July 2026 release as reported by secondary sources. They are not checked against the handbook.",

    "el.1": "Name of process, machine and location",
    "el.2": "Reference numbers of process and machine",
    "el.3": "People who performed the study and the measurements",
    "el.4": "Time and duration of data collection",
    "el.5": "Part name and number",
    "el.6": "Characteristic and specification limits",
    "el.7": "Technical conditions of the study",
    "el.8": "Deviations from defined stable operating conditions",
    "el.9": "Number of values used for the calculation",
    "el.10": "Sampling frequency and subgroup size",
    "el.11": "Histogram",
    "el.12": "Run chart",
    "el.13": "Probability plot",
    "el.14": "Control chart for the stability assessment",
    "el.15": "Estimated location parameter and method",
    "el.16": "Estimated variation parameter and method",
    "el.17": "Distribution model",
    "el.18": "Requirements and calculation method",
    "el.19": "Calculated indices and estimated share outside specification",
    "el.20": "Conclusions and recommendations",
    "el.21": "Time-dependent distribution model",
    "el.22": "Measurement uncertainty and guard band",

    "f.process": "Process",
    "f.machine": "Machine",
    "f.site": "Location",
    "f.process_ref": "Process no.",
    "f.machine_ref": "Machine no.",
    "f.part_name": "Part name",
    "f.part_number": "Part no.",
    "f.characteristic": "Characteristic",
    "f.unit": "Unit",
    "f.lsl": "Lower limit LSL",
    "f.usl": "Upper limit USL",
    "f.tolerance": "Tolerance T",
    "f.target": "Target Tm",
    "f.start": "Start",
    "f.end": "End",
    "f.duration": "Duration",
    "f.n_total": "Values in the file (ntot)",
    "f.n_used": "Values used (neff)",
    "f.n_marked": "Marked invalid",
    "f.n_unused": "Valid but not used",
    "f.subgroup_size": "Subgroup size n",
    "f.subgroups": "Number of subgroups k",
    "f.frequency_measured": "Sampling interval from the time stamps (median)",
    "f.frequency_text": "Sampling frequency (author)",
    "f.chart": "Chart",
    "f.risk": "Chart risk alpha",
    "f.criteria": "Criteria applied",
    "f.stable": "Stability",
    "f.mean": "Mean",
    "f.median": "Median X50%",
    "f.sd": "Standard deviation s",
    "f.q_low": "Quantile X0.135%",
    "f.q_high": "Quantile X99.865%",
    "f.spread": "99.73 % spread X99.865% - X0.135%",
    "f.ci": "{level} confidence interval",
    "f.method": "Method",
    "f.normality": "Normality test",
    "f.target_class": "Characteristic class",
    "f.target_p": "Target for {name}",
    "f.target_pk": "Target for {name}",
    "f.target_base": "Base sample size",
    "f.target_used": "Sample size used",
    "f.confidence_est": "Confidence of the index intervals",
    "f.confidence_target": "Confidence of the target adjustment",
    "f.index": "Index",
    "f.value": "Value",
    "f.lower": "Lower limit",
    "f.upper": "Upper limit",
    "f.verdict": "Verdict",
    "f.target_col": "Target",
    "f.below_lsl": "Below LSL",
    "f.above_usl": "Above USL",
    "f.total_out": "Total outside",
    "f.model": "Model",
    "f.controlled": "Controlled stable",
    "f.uncertainty": "Expanded uncertainty U",
    "f.coverage": "Coverage factor k",
    "f.std_uncertainty": "Standard uncertainty u = U / k",
    "f.guard_band": "Guard band g = {z} * u (risk {risk})",
    "f.accept_low": "Acceptance lower limit LSL + g",
    "f.accept_high": "Acceptance upper limit USL - g",
    "f.col_row": "File row",
    "f.col_value": "Value",
    "f.col_reason": "Reason",
    "f.col_by": "Marked by",
    "f.col_at": "Marked at",
    "f.moving": "Moving sample",
    "v.moving_line": "size {n}. It grows from 1 after the start and after every restart. {k} restart(s), listed in annex A. A moving range never spans a restart.",
    "f.restarts_title": "Restarts of the individuals chart",
    "f.phase": "Phase {k}",
    "v.phase_line": "from file row {row}: {n} values, centre line {mu}, sigma {sigma}. The limits of this phase use only its own values.",
    "f.col_phase": "Limits",
    "v.new_limits": "new limits from here",
    "x.sheet_summary": "Summary", "x.sheet_elements": "Report elements", "x.sheet_data": "Data",
    "x.sheet_charts": "Control charts", "x.sheet_check": "Check", "x.sheet_annex": "Annex", "x.sheet_log": "Log",
    "x.col_no": "No.", "x.col_element": "Element", "x.col_item": "Item", "x.col_value": "Value",
    "x.ci_low": "Interval, lower", "x.ci_high": "Interval, upper",
    "x.col_pos": "No.", "x.col_used": "Used (1 = yes)", "x.col_status": "Status", "x.col_subgroup": "Subgroup",
    "x.col_time": "Time", "x.col_restart": "Restart before this value", "x.col_label": "Label",
    "x.col_action": "Action", "x.col_n": "Values", "x.col_positions": "Positions (No.)",
    "x.status_used": "used", "x.status_invalid": "marked invalid", "x.status_unused": "not used",
    "x.restart": "restart", "x.restart_phase": "restart, new limits",
    "x.action_mark_invalid": "marked invalid", "x.action_restore": "restored", "x.action_restart": "chart restarted",
    "x.action_restart_phase": "chart restarted, new limits", "x.action_unrestart": "restart removed",
    "x.figures_note": "The histogram, run chart and probability plot (elements 11 to 13) are in the HTML report. The control charts are on the sheet 'Control charts'.",
    "x.digest": "Integrity digest of the archive (SHA-256)",
    "x.check_title": "Check with Excel formulas",
    "x.check_note": "The blue cells are inputs. The other cells are Excel formulas that recalculate the normal-distribution results from the sheet 'Data'. Only the values with 1 in the column 'Used' count. Excel calculates the formulas when it opens the file. The column 'Program' holds the numbers of this report.",
    "x.check_not_normal": "The indices of this report come from a fitted distribution ({name}, method .{method}). The formulas below recalculate the normal distribution only. They do not check this report.",
    "x.check_item": "Quantity", "x.check_program": "Program", "x.check_excel": "Excel formula", "x.check_diff": "Difference",
    "x.check_result": "Check", "x.check_agrees": "agrees", "x.check_differs": "differs",
    "x.check_tol": "Relative tolerance of the comparison", "x.check_conf": "Confidence level of the interval",
    "x.check_n": "n (values used)", "x.check_ci_low": "{name}, interval lower", "x.check_ci_high": "{name}, interval upper",
    "x.check_ppm": "Share outside the specification (ppm)",
    "x.chart_point": "Value", "x.chart_loc": "Location chart", "x.chart_var": "Variation chart",
    "x.dataset_title": "Data with marks",
    "f.none": "No values were marked invalid.",
    "f.unused_labels": "Subgroups left out: {labels}",
    "f.engine": "Software version",
    "f.fingerprint": "Parameter fingerprint",
    "f.edition": "Handbook edition for targets",
    "f.source_file": "Source file",
    "f.source_hash": "Source file SHA-256",
    "f.archive_digest": "Archive digest (SHA-256)",
    "f.stability_mode": "Decision on alarms",
    "f.customer": "Customer / parameter set",

    "v.yes": "yes",
    "v.no": "no",
    "v.normal_total": "Normal distribution, total standard deviation. For a normal distribution the General Geometric method (.G) and the z-score method (.Z) give the same result.",
    "v.normal_assumed": "Normal distribution, assumed",
    "v.mean_method": "Arithmetic mean of all values used (equals the median X50% of the fitted normal distribution)",
    "v.sd_method": "Sample standard deviation of all values used, n - 1 in the denominator",
    "v.mode_random_range": "unstable only when the alarms exceed what chance explains",
    "v.mode_strict": "any alarm means unstable",
    "v.class_unknown": "Not established",
    "v.class_statistical_control": "Stable: in statistical control",
    "v.class_in_control": "Stable: controlled stable",
    "v.class_unstable": "Stability requirements not met",
    "v.class_not_tested": "Not tested in a machine study",
    "v.verdict_meets": "Met, also at the lower confidence limit",
    "v.verdict_meets_estimate_only": "Estimate met, lower confidence limit below target",
    "v.verdict_fails": "Not met",
    "v.verdict_none": "No target",
    "v.class_critical": "Critical",
    "v.class_major": "Major",
    "v.class_minor": "Minor",
    "v.class_others": "Others",
    "v.chart_xbar-s": "X-bar and s chart",
    "v.chart_xbar-r": "X-bar and R chart",
    "v.chart_median-r": "Median and range chart",
    "fig.series.median": "subgroup medians",
    "v.chart_imr": "Individuals and moving range chart",
    "v.model_unknown": "Not given",
    "v.model_A1": "A1: location and variation constant, normal",
    "v.model_A2": "A2: constant, not normal",
    "v.model_B": "B: variation changes",
    "v.model_C1": "C1: location random, normal",
    "v.model_C2": "C2: location random, not normal",
    "v.model_C3": "C3: location trend",
    "v.model_C4": "C4: systematic and random location change",
    "v.model_D": "D: location and variation change",
    "v.rule_beyond_limits": "point beyond a control limit",
    "v.rule_run": "run of {n} points on one side",
    "v.rule_trend": "trend of {n} points",
    "v.rule_middle_third": "middle third",
    "v.rule_two_of_three_beyond_2s": "2 of 3 beyond 2 sigma",
    "v.rule_four_of_five_beyond_1s": "4 of 5 beyond 1 sigma",
    "v.rule_fifteen_within_1s": "15 within 1 sigma",
    "v.points_checked": "{n} alarm point(s) among {k} points checked; {expected} expected by chance, {threshold} allowed",
    "v.p_value": "{test}: p = {p}",
    "v.period_from_data": "from the time stamps of the data",
    "v.interval_min": "{value} min",
    "v.not_for_machine": "A machine performance study does not test stability, so no control chart is assessed. The run chart (element 12) is used to judge trends qualitatively.",
    "v.reason_machine": "machine performance study: stability is not tested",
    "v.reason_preliminary": "preliminary study: stability cannot be proven yet",
    "v.reason_stable": "stability is proven, so the capability name applies",
    "v.reason_not_proven": "stability is not proven, so the performance name applies",

    "c.names": "The indices are reported as {p} and {pk}: {reason}.",
    "c.met": "{name} = {value} meets the target {target}, also at the lower {level} bound {lower}.",
    "c.met_estimate": "{name} = {value} reaches the target {target}, but the lower {level} bound {lower} does not.",
    "c.fails": "{name} = {value} does not reach the target {target}.",
    "c.no_target": "No target values were given. The indices are reported without a verdict.",
    "c.target_blocked": "A critical characteristic needs the full sample of {base}. No reduced target exists, so no verdict is given.",
    "c.stability_statistical_control": "The control charts show a process in statistical control (model {model}).",
    "c.stability_in_control": "The control charts show a process that is controlled stable.",
    "c.stability_unstable": "The stability requirements are not met. Find and remove the special causes before claiming capability.",
    "c.stability_unknown": "Stability is not established. Choose the time-dependent model to name the indices as capability indices.",
    "c.stability_not_tested": "Stability was not tested.",
    "c.alarms": "{n} alarm point(s) on the control charts.",
    "c.not_normal": "The normality test gives p = {p}. The indices assume a normal distribution, so read them with care.",
    "c.sample_small": "{n} values are below the base sample size {base}. Intervals are wider and targets are less certain.",
    "c.marked": "{n} value(s) were marked invalid and left out of the calculation. See Annex A.",
    "c.dropped": "{count} subgroup(s) were left out because values were marked invalid: {labels}.",
    "v.dist_normal": "Normal", "v.dist_lognormal": "Lognormal", "v.dist_weibull": "Weibull", "v.dist_gamma": "Gamma",
    "v.dist_johnson_su": "Johnson SU", "v.dist_box_cox": "Box-Cox transformed normal",
    "v.dist_mixture": "Mixture of normal distributions", "v.dist_empirical": "Empirical quantiles",
    "v.how_auto": "chosen by the program: smallest AIC", "v.how_manual": "chosen by the author",
    "v.fitted_model": "{name}, fitted to the values used ({how}). Parameters: {params}",
    "v.fit_quality": "AIC {aic}, Anderson-Darling {ad}. These describe the fit. They are not tests.",
    "v.method_G": "General Geometric method (.G): quantiles X0.135 %, X50 %, X99.865 % of the fitted distribution. Interval: {interval}.",
    "v.method_Z": "z-score method (.Z): the shares outside the limits are taken from the fitted distribution and turned into z values. Interval: {interval}.",
    "v.interval_boot": "bootstrap, {used} of {requested} resamples, seed {seed}",
    "v.interval_none": "none, so a target is judged on the estimate alone",
    "v.median_fitted": "Median X50% of the fitted distribution",
    "v.verdict_meets_no_interval": "Estimate met, no interval available",
    "c.fitted": "The indices use the {name} distribution fitted to the data (method .{method}). The distribution was {how}.",
    "c.met_no_interval": "{name} = {value} reaches the target {target}. No confidence interval is available.",
    "c.no_interval": "No confidence interval is available, so the targets are judged on the estimates alone.",
    "fig.hist.fit_dist": "fitted {name}", "fig.prob.fit_dist": "fitted {name}",
    "c.one_sided": "One-sided specification: only the location index is given.",
    "c.overall_met": "Overall: all requirements are met, also at the lower confidence bounds.",
    "c.overall_not_met": "Overall: not all requirements are met.",
    "c.recommendations": "Recommendations and actions of the author",

    "fig.hist.title": "Histogram with specification limits",
    "fig.hist.x": "Value",
    "fig.hist.y": "Count",
    "fig.hist.bars": "values",
    "fig.hist.fit": "fitted normal",
    "fig.hist.spec": "specification limits",
    "fig.run.title": "Run chart of the values in sequence",
    "fig.run.x": "Sequence number",
    "fig.run.y": "Value",
    "fig.run.used": "used",
    "fig.run.invalid": "marked invalid",
    "fig.run.unused": "valid, not used",
    "fig.prob.title": "Normal probability plot",
    "fig.prob.x": "Value",
    "fig.prob.y": "Cumulative probability, %",
    "fig.prob.data": "values",
    "fig.prob.fit": "fitted normal",
    "fig.target": "Tm",
    "fig.loc.title": "Location chart: {series}",
    "fig.var.title": "Variation chart: {series}",
    "fig.series.mean": "subgroup mean",
    "fig.series.individual": "individual value",
    "fig.series.s": "subgroup standard deviation s",
    "fig.series.r": "subgroup range R",
    "fig.series.mr": "moving range",
    "fig.x": "Subgroup / point",
    "fig.y": "Value",
    "fig.ucl": "UCL",
    "fig.cl": "CL",
    "fig.lcl": "LCL",
    "fig.point": "point",
    "fig.alarm": "alarm",
}

ZH = {
    "doc.title": "製程研究報告",
    "doc.subtitle": "機器性能、製程性能與製程能力（AIAG-VDA SPC 手冊）",
    "doc.report_id": "報告編號",
    "doc.created": "製作時間",
    "doc.stage_machine": "研究類型：機器性能（Pm/Pmk）",
    "doc.stage_preliminary": "研究類型：初期製程性能（Pp/Ppk）",
    "doc.stage_production": "研究類型：製程性能或能力（Pp/Ppk 或 Cp/Cpk）",
    "doc.element": "元素",
    "doc.list_sep": "、",
    "doc.not_given": "未填寫",
    "doc.not_applicable": "不適用",
    "doc.yes": "是",
    "doc.no": "否",
    "doc.annex_a": "附錄 A：標記為無效的值",
    "doc.annex_b": "附錄 B：可追溯資訊",
    "doc.form": "表單", "v.revision": "版次", "doc.customer_fields": "{name} 要求的資訊",
    "f.profile": "客戶專屬設定", "f.profile_deviations": "與客戶設定不同的項目", "v.none": "無",
    "doc.agreed": "本報告的格式與內容須由客戶與供應商協議。",
    "doc.draft_note": "依 AIAG-VDA SPC Yellow Volume 草案（2026 年 2 月）計算。除非客戶協議另有規定，目標值僅為示例。",
    "doc.final_note": "目標值採用二手資料所述的 2026 年 7 月正式版規則，尚未對照手冊驗證。",

    "el.1": "製程、機器與地點名稱",
    "el.2": "製程與機器編號",
    "el.3": "執行研究與量測的人員",
    "el.4": "資料收集的時間與期間",
    "el.5": "零件名稱與編號",
    "el.6": "特性與規格界限",
    "el.7": "研究的技術條件",
    "el.8": "偏離穩定運行條件的紀錄",
    "el.9": "計算用的資料數",
    "el.10": "抽樣頻率與子組大小",
    "el.11": "直方圖",
    "el.12": "時間值圖（推移圖）",
    "el.13": "機率圖",
    "el.14": "穩定性評估管制圖",
    "el.15": "位置估計值與方法",
    "el.16": "變異估計值與方法",
    "el.17": "分配模型",
    "el.18": "能力要求與計算方法",
    "el.19": "指標計算結果與估計的規格外比例",
    "el.20": "結論與建議",
    "el.21": "時間相依分配模型",
    "el.22": "量測不確定度與 Guard Band",

    "f.process": "製程",
    "f.machine": "機器",
    "f.site": "地點",
    "f.process_ref": "製程編號",
    "f.machine_ref": "機器編號",
    "f.part_name": "零件名稱",
    "f.part_number": "零件編號",
    "f.characteristic": "特性",
    "f.unit": "單位",
    "f.lsl": "規格下限 LSL",
    "f.usl": "規格上限 USL",
    "f.tolerance": "公差 T",
    "f.target": "目標值 Tm",
    "f.start": "開始",
    "f.end": "結束",
    "f.duration": "期間",
    "f.n_total": "檔案中的資料數（ntot）",
    "f.n_used": "採用的資料數（neff）",
    "f.n_marked": "標記為無效",
    "f.n_unused": "有效但未採用",
    "f.subgroup_size": "子組大小 n",
    "f.subgroups": "子組數 k",
    "f.frequency_measured": "由時間戳記得出的抽樣間隔（中位數）",
    "f.frequency_text": "抽樣頻率（作者填寫）",
    "f.chart": "管制圖",
    "f.risk": "管制圖風險 alpha",
    "f.criteria": "採用的判異準則",
    "f.stable": "穩定性",
    "f.mean": "平均值",
    "f.median": "中位數 X50%",
    "f.sd": "標準差 s",
    "f.q_low": "分位數 X0.135%",
    "f.q_high": "分位數 X99.865%",
    "f.spread": "99.73 % 變異範圍 X99.865% - X0.135%",
    "f.ci": "{level} 信賴區間",
    "f.method": "方法",
    "f.normality": "常態性檢定",
    "f.target_class": "特性分級",
    "f.target_p": "{name} 的目標",
    "f.target_pk": "{name} 的目標",
    "f.target_base": "基準樣本數",
    "f.target_used": "實際樣本數",
    "f.confidence_est": "指標區間的信賴水準",
    "f.confidence_target": "目標值調整的信賴水準",
    "f.index": "指標",
    "f.value": "數值",
    "f.lower": "下限",
    "f.upper": "上限",
    "f.verdict": "判定",
    "f.target_col": "目標",
    "f.below_lsl": "低於 LSL",
    "f.above_usl": "高於 USL",
    "f.total_out": "合計規格外",
    "f.model": "模型",
    "f.controlled": "管制受控",
    "f.uncertainty": "擴展不確定度 U",
    "f.coverage": "涵蓋因子 k",
    "f.std_uncertainty": "標準不確定度 u = U / k",
    "f.guard_band": "Guard Band g = {z} * u（風險 {risk}）",
    "f.accept_low": "驗收下限 LSL + g",
    "f.accept_high": "驗收上限 USL - g",
    "f.col_row": "檔案列",
    "f.col_value": "數值",
    "f.col_reason": "理由",
    "f.col_by": "標記人員",
    "f.col_at": "標記時間",
    "f.moving": "移動樣本",
    "v.moving_line": "大小 {n}。開始時與每次重啟後由 1 逐步增加。{k} 個重啟，列於附錄 A。移動全距不會跨過重啟點。",
    "f.restarts_title": "個別值圖的重啟",
    "f.phase": "第 {k} 階段",
    "v.phase_line": "自檔案第 {row} 列起：{n} 筆，中心線 {mu}，σ {sigma}。此階段的界限只用它自己的資料計算。",
    "f.col_phase": "界限",
    "v.new_limits": "此起使用新界限",
    "x.sheet_summary": "摘要", "x.sheet_elements": "報告要素", "x.sheet_data": "資料",
    "x.sheet_charts": "管制圖", "x.sheet_check": "驗算", "x.sheet_annex": "附錄", "x.sheet_log": "紀錄",
    "x.col_no": "編號", "x.col_element": "要素", "x.col_item": "項目", "x.col_value": "內容",
    "x.ci_low": "區間下限", "x.ci_high": "區間上限",
    "x.col_pos": "編號", "x.col_used": "採用（1 = 是）", "x.col_status": "狀態", "x.col_subgroup": "子組",
    "x.col_time": "時間", "x.col_restart": "此值之前重啟", "x.col_label": "標籤",
    "x.col_action": "動作", "x.col_n": "筆數", "x.col_positions": "位置（編號）",
    "x.status_used": "採用", "x.status_invalid": "標記無效", "x.status_unused": "未採用",
    "x.restart": "重啟", "x.restart_phase": "重啟，新界限",
    "x.action_mark_invalid": "標記無效", "x.action_restore": "還原", "x.action_restart": "管制圖重啟",
    "x.action_restart_phase": "管制圖重啟，新界限", "x.action_unrestart": "取消重啟",
    "x.figures_note": "直方圖、時間值圖與機率圖（要素 11 至 13）在 HTML 報告中。管制圖在工作表「管制圖」。",
    "x.digest": "歸檔的完整性摘要（SHA-256）",
    "x.check_title": "以 Excel 公式驗算",
    "x.check_note": "藍色儲存格是輸入。其餘儲存格是 Excel 公式，由工作表「資料」重新計算常態分配的結果，只有「採用」欄為 1 的值才計入。Excel 開啟檔案時會計算公式。「程式」欄是本報告的數字。",
    "x.check_not_normal": "本報告的指標來自配適的分配（{name}，方法 .{method}）。下方公式只重算常態分配，不能用來驗算本報告。",
    "x.check_item": "量", "x.check_program": "程式", "x.check_excel": "Excel 公式", "x.check_diff": "差",
    "x.check_result": "驗算", "x.check_agrees": "相符", "x.check_differs": "不符",
    "x.check_tol": "比對的相對容許差", "x.check_conf": "區間的信賴水準",
    "x.check_n": "n（採用的資料筆數）", "x.check_ci_low": "{name} 區間下限", "x.check_ci_high": "{name} 區間上限",
    "x.check_ppm": "規格外比例（ppm）",
    "x.chart_point": "值", "x.chart_loc": "位置圖", "x.chart_var": "變異圖",
    "x.dataset_title": "資料與標記",
    "f.none": "沒有值被標記為無效。",
    "f.unused_labels": "排除的子組：{labels}",
    "f.engine": "軟體版本",
    "f.fingerprint": "參數指紋",
    "f.edition": "目標值採用的手冊版本",
    "f.source_file": "來源檔案",
    "f.source_hash": "來源檔案 SHA-256",
    "f.archive_digest": "歸檔摘要（SHA-256）",
    "f.stability_mode": "警報的判定方式",
    "f.customer": "客戶／參數組",

    "v.yes": "是",
    "v.no": "否",
    "v.normal_total": "常態分配，使用總標準差。常態分配時，General Geometric 法（.G）與 z-Score 法（.Z）結果相同。",
    "v.normal_assumed": "常態分配（假設）",
    "v.mean_method": "所有採用資料的算術平均值（等於配適常態分配的中位數 X50%）",
    "v.sd_method": "所有採用資料的樣本標準差，分母為 n - 1",
    "v.mode_random_range": "警報數超過機率可解釋的範圍才判為不穩定",
    "v.mode_strict": "只要有警報就判為不穩定",
    "v.class_unknown": "未能確立",
    "v.class_statistical_control": "穩定：統計受控",
    "v.class_in_control": "穩定：管制受控",
    "v.class_unstable": "未達穩定性要求",
    "v.class_not_tested": "機器性能研究不做穩定性檢定",
    "v.verdict_meets": "達標，信賴下限也達標",
    "v.verdict_meets_estimate_only": "估計值達標，但信賴下限低於目標",
    "v.verdict_fails": "未達標",
    "v.verdict_none": "未設目標",
    "v.class_critical": "關鍵",
    "v.class_major": "重要",
    "v.class_minor": "次要",
    "v.class_others": "其他",
    "v.chart_xbar-s": "X̄-s 圖",
    "v.chart_xbar-r": "X̄-R 圖",
    "v.chart_median-r": "中位數與全距圖",
    "fig.series.median": "子組中位數",
    "v.chart_imr": "個別值與移動全距圖",
    "v.model_unknown": "未填寫",
    "v.model_A1": "A1：位置與變異恆定，常態",
    "v.model_A2": "A2：恆定，非常態",
    "v.model_B": "B：變異改變",
    "v.model_C1": "C1：位置隨機，常態",
    "v.model_C2": "C2：位置隨機，非常態",
    "v.model_C3": "C3：位置有趨勢",
    "v.model_C4": "C4：位置為系統性加隨機變化",
    "v.model_D": "D：位置與變異都改變",
    "v.rule_beyond_limits": "點超出管制界限",
    "v.rule_run": "同一側連續 {n} 點",
    "v.rule_trend": "連續 {n} 點趨勢",
    "v.rule_middle_third": "中間三分之一",
    "v.rule_two_of_three_beyond_2s": "3 點中 2 點超過 2 個標準差",
    "v.rule_four_of_five_beyond_1s": "5 點中 4 點超過 1 個標準差",
    "v.rule_fifteen_within_1s": "連續 15 點在 1 個標準差內",
    "v.points_checked": "檢查 {k} 點，出現 {n} 個警報點；機率預期 {expected} 點，容許 {threshold} 點",
    "v.p_value": "{test}：p = {p}",
    "v.period_from_data": "取自資料的時間戳記",
    "v.interval_min": "{value} 分鐘",
    "v.not_for_machine": "機器性能研究不檢定穩定性，所以不評估管制圖。以時間值圖（元素 12）定性判斷趨勢。",
    "v.reason_machine": "機器性能研究：不做穩定性檢定",
    "v.reason_preliminary": "初期研究：尚無法證明穩定性",
    "v.reason_stable": "已證明穩定，所以適用「能力」的名稱",
    "v.reason_not_proven": "尚未證明穩定，所以適用「性能」的名稱",

    "c.names": "指標應稱為 {p} 與 {pk}：{reason}。",
    "c.met": "{name} = {value}，達到目標 {target}，連 {level} 信賴下限 {lower} 也達標。",
    "c.met_estimate": "{name} = {value}，達到目標 {target}，但 {level} 信賴下限 {lower} 未達標。",
    "c.fails": "{name} = {value}，未達目標 {target}。",
    "c.no_target": "未設定目標值，指標只呈現數值，不做判定。",
    "c.target_blocked": "關鍵特性必須取足 {base} 件，沒有縮減樣本後的目標值，所以不做判定。",
    "c.stability_statistical_control": "管制圖顯示製程處於統計受控（模型 {model}）。",
    "c.stability_in_control": "管制圖顯示製程屬於管制受控。",
    "c.stability_unstable": "未達穩定性要求。要宣稱能力之前，請先找出並排除特殊原因。",
    "c.stability_unknown": "穩定性未能確立。請選定時間相依模型，才能把指標稱為能力指標。",
    "c.stability_not_tested": "未檢定穩定性。",
    "c.alarms": "管制圖上有 {n} 個警報點。",
    "c.not_normal": "常態性檢定的 p = {p}。指標假設為常態分配，請謹慎解讀。",
    "c.sample_small": "{n} 筆低於基準樣本數 {base}，區間較寬，目標值的把握較低。",
    "c.marked": "有 {n} 筆被標記為無效，並已排除於計算之外，見附錄 A。",
    "c.dropped": "因為有值被標記為無效，已排除 {count} 個子組：{labels}。",
    "v.dist_normal": "常態", "v.dist_lognormal": "對數常態", "v.dist_weibull": "韋伯", "v.dist_gamma": "伽瑪",
    "v.dist_johnson_su": "Johnson SU 分配", "v.dist_box_cox": "Box-Cox 轉換後為常態",
    "v.dist_mixture": "常態分配的混合", "v.dist_empirical": "經驗分位數",
    "v.how_auto": "由程式選擇：AIC 最小", "v.how_manual": "由作者指定",
    "v.fitted_model": "{name}，以採用的資料配適（{how}）。參數：{params}",
    "v.fit_quality": "AIC {aic}，Anderson-Darling {ad}。這些只描述配適程度，不是檢定。",
    "v.method_G": "General Geometric 法（.G）：取配適分配的分位數 X0.135 %、X50 %、X99.865 %。區間：{interval}。",
    "v.method_Z": "z-Score 法（.Z）：由配適分配取得規格外比例，再換算為 z 值。區間：{interval}。",
    "v.interval_boot": "Bootstrap，重抽 {requested} 次中有 {used} 次可用，種子 {seed}",
    "v.interval_none": "無，因此目標值只用估計值判定",
    "v.median_fitted": "配適分配的中位數 X50%",
    "v.verdict_meets_no_interval": "估計值達標，無信賴區間",
    "c.fitted": "指標使用配適於資料的{name}分配（方法 .{method}）。分配為{how}。",
    "c.met_no_interval": "{name} = {value} 達到目標 {target}。沒有信賴區間。",
    "c.no_interval": "沒有信賴區間，因此目標值只用估計值判定。",
    "fig.hist.fit_dist": "配適的{name}", "fig.prob.fit_dist": "配適的{name}",
    "c.one_sided": "單邊規格：只提供位置指標。",
    "c.overall_met": "整體：所有要求都達標，連信賴下限也達標。",
    "c.overall_not_met": "整體：並非所有要求都達標。",
    "c.recommendations": "作者的建議與措施",

    "fig.hist.title": "直方圖與規格界限",
    "fig.hist.x": "數值",
    "fig.hist.y": "筆數",
    "fig.hist.bars": "資料",
    "fig.hist.fit": "配適的常態分配",
    "fig.hist.spec": "規格界限",
    "fig.run.title": "依順序排列的時間值圖",
    "fig.run.x": "順序編號",
    "fig.run.y": "數值",
    "fig.run.used": "採用",
    "fig.run.invalid": "標記為無效",
    "fig.run.unused": "有效但未採用",
    "fig.prob.title": "常態機率圖",
    "fig.prob.x": "數值",
    "fig.prob.y": "累積機率，%",
    "fig.prob.data": "資料",
    "fig.prob.fit": "配適的常態分配",
    "fig.target": "Tm",
    "fig.loc.title": "位置管制圖：{series}",
    "fig.var.title": "變異管制圖：{series}",
    "fig.series.mean": "子組平均值",
    "fig.series.individual": "個別值",
    "fig.series.s": "子組標準差 s",
    "fig.series.r": "子組全距 R",
    "fig.series.mr": "移動全距",
    "fig.x": "子組／點",
    "fig.y": "數值",
    "fig.ucl": "管制上限",
    "fig.cl": "中心線",
    "fig.lcl": "管制下限",
    "fig.point": "點",
    "fig.alarm": "警報",
}

TEXTS = {"en": EN, "zh-TW": ZH}


def T(lang: str, key: str, **params) -> str:
    table = TEXTS.get(lang, EN)
    template = table.get(key, EN.get(key, key))
    return template.format(**params) if params else template
